(library (foo bar)
  (export foo)
  (import (rnrs base (6)))
  (define foo 42)
)

(library (xyz)
  (export bar)
  (import (draft)
	  (rnrs base (6))
          (foo bar))
  (draft-print 'foo)
  (draft-print foo)
  (define bar foo)
)
